### ISSUE TITLE
Rules 'Will be ignored if config file is used' are not ignored 

### ISSUE THREAD

**Issue by danaki** [pfefferle/atom-php-cs-fixer#56]
<img width="1084" alt="screen shot 2017-01-19 at 22 24 33" src="https://cloud.githubusercontent.com/assets/1043805/22123946/79ba5a14-de96-11e6-94bb-ebd02a6d4988.png">

**Comment by danaki** [comment]
atom-php-cs-fixer version 4.1.0

As I can see from the sources PHP-CS-Fixer also must be skipped once config file path is provided and it's worth to add such note into settings screen too.

**Comment by joseluisq** [comment]
same error! 

![image](https://cloud.githubusercontent.com/assets/1700322/22253835/481ebbba-e253-11e6-88b6-f894a859db3f.png)

`atom-php-cs-fixer version 4.1.0`

**Comment by pfefferle** [comment]
@joseluisq this is not the same error, you are using an old version of PHP-CS-Fixer! please update to version >= 2.0.0.

**Comment by joseluisq** [comment]
@pfefferle sorry :sweat_smile: 
I have updated `php-cs-fixer` to `v2.0.0`
Now works fine!

**Comment by pfefferle** [comment]
@joseluisq no problem :wink:

**Comment by pfefferle** [comment]
@danaki I think this problem is solved with the github version, I have to test it and release a new version.

**Comment by tgomesfork** [comment]
I still have this problem, or am I doing something wrong?

![image](https://cloud.githubusercontent.com/assets/24874037/26242353/06957238-3c80-11e7-8bad-eef2962c87ad.png)

php-cs-fixer v2.3.1
atom php-cs-fixer 4.1.0
